### ISSUE TITLE
Reserve document number in the Pending Documents register

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-joins#4]
Please reserve a document number in the Pending Documents register, and then add the number to the [OGC API - Joins - Part 1 Core.adoc](https://github.com/opengeospatial/ogcapi-joins/blob/master/sources/core/standard/OGC%20API%20-%20Joins%20-%20Part%201%20Core.adoc) file on the `:docnumber:` field.

**Comment by latvap** [comment]
Document number added.
